### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by HuixingWong** [JackieXie168/skim#2]
This is a great reader，support for dark mode would be even better

**Comment by memeplex** [comment]
What do you mean? I've been using this app for 5 minutes and there is both dark mode support at the GUI level and an option to invert document colors in dark mode. What's missing?

**Comment by HuixingWong** [comment]
> 

Where is the ‘option to invert document colors in dark mode‘ ， I didn't find it.

**Comment by HuixingWong** [comment]
Got it. Thank you.

**Comment by r3a1d3a1** [comment]
I can't seem to find the option to invert colors of a PDF. Any hints?!
